parameters:
    phpbb.titania.root_path: '%core.root_path%ext/phpbb/titania/'
    tables:
        titania:
            attachments: '%core.table_prefix%_attachments'
            attention: '%core.table_prefix%_attention'
            autmod_queue: '%core.table_prefix%_automod_queue'
            authors: '%core.table_prefix%_authors'
            categories: '%core.table_prefix%_categories'
            contribs: '%core.table_prefix%_contribs'
            contrib_coauthors: '%core.table_prefix%_contrib_coauthors'
            contrib_faq: '%core.table_prefix%_contrib_faq'
            contrib_in_categories: '%core.table_prefix%_contrib_in_categories'
            posts: '%core.table_prefix%_posts'
            queue: '%core.table_prefix%_queue'
            ratings: '%core.table_prefix%_ratings'
            revisions: '%core.table_prefix%_revisions'
            revisions_phpbb: '%core.table_prefix%_revisions_phpbb'
            tag_applied: '%core.table_prefix%_tag_applied'
            tag_fields: '%core.table_prefix%_tag_fields'
            tag_types: '%core.table_prefix%_tag_types'
            topics: '%core.table_prefix%_topics'
            topics_posted: '%core.table_prefix%_topics_posted'
            track: '%core.table_prefix%_track'
            watch: '%core.table_prefix%_watch'