parameters:
    phpbb.titania.root_path: '%core.root_path%ext/phpbb/titania/'
    tables.titania.attachments: 'customisation_attachments'
    tables.titania.attention: 'customisation_attention'
    tables.titania.autmod_queue: 'customisation_automod_queue'
    tables.titania.authors: 'customisation_authors'
    tables.titania.categories: 'customisation_categories'
    tables.titania.contribs: 'customisation_contribs'
    tables.titania.contrib_coauthors: 'customisation_contrib_coauthors'
    tables.titania.contrib_faq: 'customisation_contrib_faq'
    tables.titania.contrib_in_categories: 'customisation_contrib_in_categories'
    tables.titania.posts: 'customisation_posts'
    tables.titania.queue: 'customisation_queue'
    tables.titania.ratings: 'customisation_ratings'
    tables.titania.revisions: 'customisation_revisions'
    tables.titania.revisions_phpbb: 'customisation_revisions_phpbb'
    tables.titania.tag_applied: 'customisation_tag_applied'
    tables.titania.tag_fields: 'customisation_tag_fields'
    tables.titania.tag_types: 'customisation_tag_types'
    tables.titania.topics: 'customisation_topics'
    tables.titania.topics_posted: 'customisation_topics_posted'
    tables.titania.track: 'customisation_track'
    tables.titania.watch: 'customisation_watch'