custdb_index:
    path: /custdb/index
    defaults: { _controller: phpbb.oberon.controller:index }

custdb_add_contribution:
    path: /custdb/add
    defaults: { _controller: phpbb.oberon.controller:add }

custdb_view_contribution:
    path: /custdb/view/{id}
    requirements:
        id: \d+
    defaults: { _controller: phpbb.oberon.controller:view, id: 0 }