imports:
    - { resource: tables.yml }

services:
    phpbb.oberon.manager:
        class: phpbb\oberon\manager\manager
        arguments:             
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@user_loader'
            - '@language'
            - '@ext.manager'
            - '%phpbb.oberon.tables%'
    phpbb.oberon.controller:
        class: phpbb\oberon\controller\oberon
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@pagination'
            - '@language'
            - '@phpbb.oberon.manager'
    phpbb.oberon.listener:
        class: phpbb\oberon\event\oberon_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
    phpbb.oberon.console.queue_manager:
        class: phpbb\oberon\console\queue_manager
        arguments:
            - '@dbal.conn'
            - '@phpbb.oberon.manager'
        tags:
            - { name: console.command }
    phpbb.oberon.console.ai_validation:
        class: phpbb\oberon\console\ai_validation
        arguments:
            - '@dbal.conn'
            - '@phpbb.oberon.manager'
        tags:
            - { name: console.command }