imports:
    - { resource: tables.yml }

services:
    battye.custdb.manager:
        class: battye\custdb\manager\manager
        arguments:             
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@user_loader'
            - '@language'
            - '%battye.custdb.tables%'
    battye.custdb.controller:
        class: battye\custdb\controller\custdb
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@pagination'
            - '@language'
            - '@battye.custdb.manager'
    battye.custdb.listener:
        class: battye\custdb\event\custdb_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
    battye.custdb.console.queue_manager:
        class: battye\custdb\console\queue_manager
        arguments:
            - '@battye.custdb.manager'
        tags:
            - { name: console.command }